name: My First Workflow

on:
  push:
    branches: [main]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: 안녕하세요 출력
        run: echo "안녕하세요"

      - name: 현재 날짜와 시간 출력
        run: date

      - name: 커밋한 사람 출력
        run: echo "커밋한 사람:${{ github.actor }}"
